const songs = [
    {
        id: 1,
        title: "Thuli Thuli Mazhaiyaai",
        lyrics: "Thuli thuli thuli mazhayaai vandhalae\nSuda suda suda maraindhae ponaalae\n\nPaarthal parka thondrum\nPerai ketka thondrum\nPoopol sirikum podhu kaatrai parandhida thondrum .\n\nSel sel avalidam sel endrae kalgal solludhada\nSol sol avalidam sol endrae nenjam kolludhada\nAzhagai manadhai parithuvitaalae ...\n\nThuli thuli thuli mazhayaai vandhalae..ehhhh\nSuda suda suda maraindhae ponaalae..ehhh\n\nDevadhai aval oru devadhai\nAzhagiya poomugam kanavae aayul thaan pothumo\nKatrilae avaladhu vaasanai\nAvalidam yosannai ketuthan pookalum pookumo\n\nNetri mela otraimudi aadum podhu\nNenjukulale minnal pookum parvai aalai thookum\nKanam parthal muthangalal theenda thondrum\nPadham rendu parkum podhu golusai marathondrum\n\nAzhagai manadhai parithuvitaalae ...\nSel sel avalidam sel endrae kalgal solludhada\nSol sol avalidam sol endrae nenjam kolludhada\n\nSalayil azhagiya mazhayil\nAvaludan pogavae yenguven thozgalil saayuven\n\nBoomiyil vizhugira velayil\nNizhalayum odipoi yendhuven nenjilae thanguven\n\nKanum podhae kanaal yennai katti potal\nKayamindri vetti potal uyirai edho seidhal\nMounamaga ullukulae pesum podhum\nAngae vandhu ottu ketal kanvil koochal potal\n\nAzhagai manadhai parithuvitaalae ...\nSel sel avalidam sel endrae kalgal solludhada\nSol sol avalidam sol endrae nenjam kolludhada\n\n{Thuli thuli thuli mazhayaai vandhalae\nSuda suda suda maraindhae ponaalae} (2)"
    },
    {
        id: 2,
        title: "Peela Peela",
        lyrics: "Yo poyah peela vidadha\nYeh venna reela suthadha\nYo poyah peela vidadha\nYeh venna reela suthadha\n\nPeela peela peela peela\nPeela vudadha\nReela reela reela reela\nReela suthadha\n\nPeela peela peela peela\nPeela vudadha\nVenna venna venavae venna\nScena podadha\n\nDai romeo\nNeeyum naanum jodiyo\nVaraevava varae vaava\nMy mamiyo\nEn babies-ku mummyo\nVarae vaava varae vaava\n\nAntha nilavayerakki\nAlava surukki naan thaaren\nAntha megatha madakki\nKaiyila adachitten paaren\n\nPeela peela peela peela\nPeela vudadha\nReela reela reela reela\nReela suthadha\n\nPeela peela peela peela\nPeela vudadha\nVenna venna venavae venna\nScena podadha\n\nNirma sundariyae\nPoppins pallazhagae\nUjala iduppathaan ullukuriyae\nLifeboy arokiyamae\nBoost energiyae\nGoldspot nenjukkulla ilukkuriyae\n\nVaama en rasnavae\nI love you\nKonjam pakkathilae neeyum vantha\nDhagam theeruthae\n\nDyanora raasavae\nLove you too\nUn kawasaki bike-u seatil\nUkkarathaan kathurukken\n\nAaja aaja\nAaja ah ah aajja\nAaja aaja aaja\nAaja honey\nAttam podalam\n\nPeela peela peela peela\nPeela vudadha\nVenna venna venavae venna\nScena podadha\n\nDai romeo\nNeeyum naanum jodiyo\nVaraevava varae vaava\nMy mamiyo\nEn babies-ku mummyo\nVarae vaava varae vaava\n\nAntha nilavayerakki\nAlava surukki naan thaaren\nAntha megatha madakki\nKaiyila adachitten paaren\n\nAppa kitta sollama vaa\nAttam podalam\nAmma kitta sollama va\nAppe tu aagalam\n\nAppa kitta sollama va\nAttam podalam\nAmma kitta sollama va\nAbscond aagalam\n\nPeela peela peela peela\nPeela vudadha\nReela reela reela reela\nReela suthadha\n\nPeela peela peela peela\nPeela vudadha\nVenna venna venave venna\nScena podadha"
    },
    {
        id: 3,
        title: "Idhu Varai",
        lyrics: "Hmm Hmm.....\nHmm Hmm....\n\nIdhu varai illadha unarvidhu\nIdhayathil undana kanavidhu\nPalithidum annalai thedidum padal kettaiyo\n\nIdhu varai illadha unarvidhu\nIdhayathil undana kanavidhu\nPalithidum annalai thedidum padal kettaiyo\n\nMoodamal moodi maraithadhu\nThaanaga poothu varughudhu\nThedamal thedi kidaithadhu ingaeee\n\nMoodamal moodi maraithadhu\nThaanaga poothu varughudhu\nThedamal thedi kidaithadhu ingaeee...\n\nIngae oru inbam vandhu niraiya\nEppodhu en unmai nilai ariya\nThaangamalum thoongamalum\nNaal selludhaeee\n\nIllamalae nitham varum kanavu\nKollamal kolla\nSugam ennendru solla\nNee thunai varavendum\nNeendavazhi en payanam\n\nHmmmm...idhuvarai\nIllaatha unarvidhu\nIdhayathai thundaakkum ninaividhu\nManadhinai mannodu\nPudhaithidum pennai nambaathae\n\nKaadhal endraal\nAthanaiyum kanavu\nKann moodiyae\nVaazhgindra uravu\nPengal endraal\nAanai kollum noiyaanathae\n\nAiyyo intha\nIlamaiyin thodakkam\nIndrae muttrupulli\nAdhai sollaamal solli\nNammai paiththiyam aakkum\nPennai thedi tholaiyaathae..."
    },
    {
        id: 4,
        title: "Kannaana Kanne",
        lyrics: "\nOru ganam oru podhum\nPiriya koodadhey\nEn uyire en uyire\nNee azhuga koodadhey\nNee kanda kanavu edhumey\nKalaiya koodadhey\nNaan liukkum naal varaikkum\nNee azhuga koodadhey\n\nKedachadha ezhakkuradhum\nEzhandhadhu kedaikiradhum\nAdhukku pazhaguradhum\nNyaayam dhaanadi...\nKuduthadha edukkuradhum\nVera onna kudukkuradhum\nNadanthatha marakkuradhum\nVazhakkam dhaanadi..\n\nKannaana kanne nee kalangadhadi\nEn uyiroda aadharam needhanadi..\nKannaana kanne nee kalangadhadi\nYaar pona enna naan irupenadi..ohh\n\nEn veral idukkula\nUn veral kedakkanum\nNasungura alavukku irukki\nNa pudikkanum\nNaan kanna thorakkaiyil\nUn mugam theriyanum\nUsurulla varaikkumae\nUnakkenna pudikkanum\nKadal alai pola unkaal thottu orasi\nKadal ulla poravan naan illa di\nKadal manna pola un kaaloda otti\nKara thaandum vara naan irupenadi\n\nKannaana kanne nee kalangadhadi\nEn uyiroda aadharam needhanadi..\nKannaana kanne nee kalangadhadi\nYaar pona enna naan irupenadi..\n\nOru ganam oru podhum\nPiriya koodadhey\nEn uyire en uyire\nNee azhuga koodadhey\nNee kanda kanavu edhumey\nKalaiya koodadhey\nNaan liukkum naal varaikkum\nNee azhuga koodadhey\n\nNitham nitham nee odanjaa\nOtta vekka naan irukken\nKitta vechu paathukuve\nUyir vaazhurendi\nPethavanga pona enna\nSathamilla un ulagil\nNitham oru mutham vekka than\nUyir vaazhurendi"
    },
    {
        id: 5,
        title: "Channa Mereya",
        lyrics: "Acha chalta hoon\n\nDuaon mein yaad rakhna\nMere zikr ka zubaan pe swaad rakhna\n\nAcha chalta hoon\nDuaon mein yaad rakhna\nMere zikr ka zubaan pe swaad rakhna\n\nDil ke sandookon mein\nMere ache kaam rakhna\nChitthi taaron mein bhi\nMera tu salaam rakhna\n\nAndhera tera maine le liya\nMera ujla sitaara tere naam kiya\n\nChanna mereya mereya\nChanna mereya mereya\nChanna mereya mereya beliya\nO piya..\n\nChanna mereya mereya\nChanna mereya mereya\nChanna mereya mereya beliya\n\nO piya..\n\nO piyaa.. piya.. piya..\nO Piyaa.. Oohh..\n\nMm.. mehfil me teri hum naa reh jo\nGham toh nahi hai, gham toh nahi hai\nQisse humare nazdeekiyon ke\nKam to nahi hai, kam to nahi hai\n\nKitni dafaa subah ko meri\nTere aangan mein baithe shaam kiya\n\nChanna mereya mereya\nChanna mereya mereya\nChanna mereya mereya beliya\nO piya..\n\nChanna mereya mereya\nChanna mereya mereya\nChanna mereya mereya beliya\nO piyaaaaaaaaa..\n\nChanna mereya mereya\nChanna mereya mereya\nChanna mereya mereya o piya"
    },
    {
        id: 6,
        title: "Enna Nadandhalum Penne",
        lyrics: "Enna Nadanthalum\nPenne Unna Vida Maten\nNee Enna Maranthaalum\nEn Manasula Neethan Ninaivu Irupa\n\nAdi Enna Nadanthalum\nPenne Unna Vida Maten\nNee Enna Maranthaalum\nEn Manasula Neethan Ninaivu Irupa\n\nManasukkul Ulla Kadhala\nPooti Veika Mudiyala Di\nIrunthaalum Manasuku Thaan\nVeliya Solla Vazhi Illa Di\n\nAdi Enna Nadanthalum\nPenne Unna Vida Maten\nNee Enna Maranthaalum\nEn Manasula Neethan Ninaivu Irupa\n\nOru Naal Nee Ennai Sandhithaal\nAdi Penne Neeyum Sindhippaal\nEnnai Yeno Pirindhu Sendru\nUn Vaazhvai Neeye Dhandithaai\n\nSari Paadhi Sari Paadhi\nNeethan En Sari Paadhi\nUyir Naadi Uyir Naadi\nEna Naanum Unai Naadi\n\nVantha Pothu Enna Thalli Enga Pora Nee?\nNee Thalli Ponathaala\nNaanum Yengi Poren Di\n\nEnna Nadanthalum\nPenne Unna Vida Maten\nNee Enna Maranthaalum\nEn Manasula Neethan Ninaivu Irupa\n\nAdi Enna Nadanthalum\nPenne Unna Vida Maten\nNee Enna Maranthaalum\nEn Manasula Neethan Ninaivu Irupa\n\nUnnoda Kangal\nVazhiyum Kanner\nVadiyum Sogam\nKavalai Vendam Poo\n\nUnnoda Kaiyil\nNaan Vanthu Serum\nAndha Naalum\nVegu Thooram Ilayo\n\nKavinganuku Kalaiyin Meedhu\nKaadhal Vandhadhu\nAndha Kalaiyin Meedhu Konda Kaadhal\nUnnai Vendrathu\nIruntha Pothum Undhan Meedhu\nKaadhal Enbathu\nEn Kanavil Vendru Vaazhvil Vendru\nUnnai Velvathu\n\nWhatever You Want\nWhatever You Need\nEnna Venum Solladi\nWhatever You Are\nWhatever You Be\nNeethan En Kaadhali\n\nEnnai Vittu Pona Ennai Seiven\nUnnudaiyadhadha Naan Irupen\nOru Murai\nEn Kanna Paathu Sonna Pothum\n\nEnna Nadanthalum\nPenne Unna Vida Maten\nNee Enna Maranthaalum\nEn Manasula Neethan Ninaivu Irupa\n\nAdi Enna Nadanthalum\nPenne Unna Vida Maten\nNee Enna Maranthaalum\nEn Manasula Neethan Ninaivu Irupa\n\nEnnai Vittu Pona Ennai Seiven\nUnnudaiyadhadha Naan Irupen\nOru Murai\nEn Kanna Paathu Sonna Pothum\n\nEnnai Vittu Pona Ennai Seiven\nUnnudaiyadhadha Naan Irupen\nOru Murai\nEn Kanna Paathu Sonna Pothum..."
    },
    {
        id: 7,
        title: "Oru Kal Oru Kannadi",
        lyrics: "Oru kal oru kannaadi\nUdaiyaamal mothi kondaal kaadhal\nOru sol sila mounangal\nPesaamal pesi kondaal kaadhal\n\nKangal rendil ...il kaadhal vanthaal ho\nKanneer matum ..mm thunai aagumae\nOh hoo hoo\n\nOru kal oru kannaadi\nUdaiyaamal mothi kondaal kaadhal\nOru sol sila mounangal\nPesaamal pesi kondaal kaadhal ...lll\n\nThimiruku maru peyar neethaanane\nThinam thinam unnaal iranthenae\nMaranthida matum maranthenae\n\nThee ena purinthum adi naanae\nThirumbavum unai thoda vanthenae\nTherindhe sugamaai erinthenae\n\nKadum visathinai eduthu kudithaalum\nAdi konja neram kazhidhae uyir pogum\nIndha kaadhalilae udanae uyir pogum\nKaadhal endraal pennae\nChithravathai thaanae\n\nOru kal oru kannaadi\nUdaiyaamal mothi kondaal kaadhal\nOru sol sila mounangal\nPesaamal pesi kondaal kaadhal ...lll\n\nUn mugam paardhae naan ezhuven\nUn kural ketaal naan ariven\nUn nizhaludanae naan varuven\n\nPunnagai seithaal uyir vaazhven\nPurakanithaal naan ennaaven\nPennae engae naan poven\n\nUn udhatukul irukum oru vaarthai\nAthai sollivitaal thodangum en vaazhkai\nUn mounathil irukum enna valigal\nKaadhal endraal mella\nSaathal endru solla\n\nOru kal oru kannaadi\nUdaiyaamal mothi kondaal kaadhal\nOru sol sila mounangal\nPesaamal pesi kondaal kaadhal ...ll"
    },
    {
        id: 8,
        title: "Pirai Thedum",
        lyrics: "{Pirai thedum iravilae uyirae\nEdhai thedi alaigiraai\nKadhai solla azhaikiren uyirae\nAnbae nee vaa} (2)\n\nIrulil kanneerum edharku\nMadiyil kan mooda vaa\n\nAzhagae intha sogam edharku\nNaan un thaayum allava\n\nUnakkena mattum vaazhum idhayam adi\nUyir ulla varai naan un adimaiyadi\n\nPirai thedum iravilae uyirae\nEdhai thedi alaigiraai\nKadhai solla azhaikiren uyirae\nAnbae nee vaa\n\nAzhuthaal un paarvaiyum\nAyanthaal un kaalgalum\nAdhikaalaiyin koodalil\nSogam theerkkum podhuma\n\nNizhal thedidum aanmaiyum\nNijam thedidum penmaiyum\nOru porvaiyil vaazhum inbam\nDheivam thantha sonthama\n\nEn aayul reghai neeyadi\nEn aani veradi\nSumai thaangum endhan kanmani\nEnnai sudum pani\n\nUnakkena mattum vaazhum idhayamadi\nUyirulla varai naan un adimaiyadi\n\nPirai thedum iravilae uyirae\nEdhai thedi alaigiraai\nKadhai solla azhaikiren uyirae\nAnbae nee vaa"
    },
    {
        id: 9,
        title: "Kannukulla",
        lyrics: "En kannukulla kathaadha\nNenjukulla nachaadha\nSolle podhum\nUn solle podhum\n\nEn anba mothom pichane\nKovam vechu thechcaane\nInnum venum\nOh innum venum\n\nVittu Pona Vaasalile\nVaazhka theera kaathirukken\nKaathilulla kaadhalellam\nKooti kaathu thaarenen naan\n\nOda oda naan mela saanjika\nTheera theera un thol illaya?\nEeram eeram kann oram medhuvaa kothume....ae\n\nOda oda naan mela saanjika\Theera theera un thol illaya?\nEeram eeram kann orama kothume....ae\n\nEn kannukulla kathaadha\nNenjukulla nachaadha\nSolle podhum\nUn solle podhum\n\nYaar pazhiyo\nYaar pizhayo\nYaar vecha kan muzhiyo\nNaan keta kelvikku\nNee mattum thaa vidaiyo\n\nEnnagum en vidhiyo...\nEnnagum en vidhiyo\nEnnagum en vidhiyo\nEnnagumo\n\nVittu Pona Vaasalile\nVaazhka theera kaathirukken\nKaathilulla kaadhalellam\nKooti kaathu thaarenen naan\n\nOda oda naan mela saanjika\nTheera theera un thol illaya?\nEeram eeram kann oram medhuvaa kothume....ae\n\nOda oda naan mela saanjika\Theera theera un thol illaya?\nEeram eeram kann orama kothume....ae\n\nAavalum aazhudhu\nPaadalum neeludhu\nYekkam illa idhu\nVer edho puriyalaye\n\nTheevaram thaangala\nTheeravum thonala\nTheevula thooki potta\nThana udanjen ulla"
    },
    {
        id: 10,
        title: "En Veetula",
        lyrics: "En veetula naan irundhenae\nEdhir veetula ava irundhalae\nLove torture panna ennaku theriyala\nAva daddy moonji sariyila\n\nAva mummy pechum pudikala\nAnaalum avala marakka mudiyala...\n\nNaan love aala pala bulbu\nVaanguna paiyaan...athanaala\nEn life-u oli veesudhae\nAva pinnaala naan kooda ponnenae\nLove-a solla\nChina phone-ula signal illa\nPochae.....vada pochae....\n\nLondon bridge is falling down-u\nLondon bridge is falling\nLondon bridge is falling\nFalling down-u\nDown-u ...falling down-u\n\nEdhukumae time illa\nSulatitaa kedikaara mulla\nAvaluku hai solla\nRehearsalu paarpen ennakulla\n\nKaathaadi pola manasu\nKaathodu ponadhae\nMedhandhu megam thottu\nMaatikichu satellite-la\nEmail ID illa athanaala\nLetter ezhudhi thandhen blood-aala\nKozhi ...blood-aala .....\n\nEn veetula naan irundhenae\nEdhir veetula ava irundhalae\nLove torture panna ennaku theriyala\nAva daddy moonji sariyila\nAva mummy pechum pudikala\nAnaalum avala marakka mudiyala...\n\nLuck ku than venum na\nLove onnum lottery chittu ila\nUzhaipu than perisu-nu naa\nFollow panna en pol aaal ila\n\nEk tujhe keliyae va\nNaa innum paakala\nIrundhum area-vil\nLove-il enna minja aal illa\nRain ippo namma kattula\nSon-in-law na kumutha vuutula\n\nJohny johny yes papa\nTelling lies no pappa\nTelling lies no pappa\nNo pappa ...quicka vaa pappa"
    },
    {
        id: 11,
        title: "Hi Sonna Podhum",
        lyrics: "Nee hai sonna podhum\nOru bodha onnu yerum\nNee thottalae podhum\nManam jivvu-nu thaan aagum\n\nNee sirichaalum morchaalum\nHeart-u beat-u yerum\nVekkam maanam edhuvum ilama\nPinnadi suthuven naanum\n\nHey cycle-u dhaan vehicle-u\nSchool bathroom sevathula kirukkalu\nCanteenukku vara sollu\nEn billa avalaiyae thara sollu\n\nAva pogum bodhu\nEn pera kaththu\nAva sirichitaana\nEn love-u settu\n\nEn classukulla\nNaan romba veththu\nIni aaga poren da\nSchool-u geththu\n\n{Naa summavae scene-u di\nIni schoolukku don-u di} (4)\n\nBook-u mela\nBook ah veppen\nNee pogum bodhu\nLook-ah veppen\n\nNalla paiyan\nPola nadippen\nEdamirunthaalum\nUnna idippen\n\nInk bottle manasu unakku\nUlla kaadhal kotti kedakku\nInk pennu summa irukku\nKaadhal ah dhaan oothu enakku\n\nGoli urunda kannu size-u\nRollu cap ah vedikkuthu manasu\nCallu panni kurala kettu\nThookaththukku vechaa vettu\n\nPakathu class-u pasanga munnaal\nDhilla nippen di\nDhilla nippen di\n\nVera evana vambu panna\nPalla odaippen di\nPalla odaippen di\n\n{Naa summavae scene-u di\nIni schoolukku don-u di} (2)\n\nHey cycle-u dhaan vehicle-u\nSchool bathroom sevathula kirukkalu\nCanteenukku vara sollu\nEn billa avalaiyae thara sollu\n\nAva pogum bodhu\nEn pera kaththu\nAva sirichitaana\nEn love-u settu\n\nEn classukulla\nNaan romba veththu\nIni aaga poren da\nSchool-u geththu\n\n{Naa summavae scene-u di\nIni schoolukku don-u di} (2)"
    },
    {
        id: 12,
        title: "Takkunu Takkunu",
        lyrics: "Ava neraa pakkaiyil\nKonja gera aaguthu\nAva gera sirikkaiyil\nManam noora norunguthu\n\nAiyo paakaatha\nEnnai thaakaadha\nIdhayam weakaaga\nUnakkaaga vaazha\n\nTakkunu takkunu\nTakkunu takkunu\nTakkunu takkunu paakaatha\nBakkunu bakkunu\nBakkunu bakkunu\nBakkunu bakkunu aakkaatha\n\nKick onnu kick onnu\nKick onnu kick onnu\nKick onnu irukkuthu paarvaiyila\nLook onnu look onnu\nLook onnu look onnu\nVituttu ponaa thappae illa\n\nEnna paakkaatha\nPaarvaiyaala ennai thaakkaadha\nEnna paakkaatha\nPaarvaiyaala enna thaakkaadha\n\nKoovi koovi vikkura caru\nRoadu mela poguthu paaru\nAthil sernthu naama pona sema joru\n\nChorus : Aamam di...\n\nArea-la kettu paaru\nEnna minja aalu yaru\nNee ok sonna life-eh thaar maaru\nChorus : Sollen di...\n\nWhite-ah dhaan\nBright-ah dhaan\nIrukkum paalu\n\nAthukku expiry date-u\nJust orae oru naalu\n\nDark-ah dhaan\nBrown-ah dhaan\nIrukkum theanu\n\nAdi adhu pol naanu\nKeda matten kannu\n\nTakkunu takkunu\nTakkunu takkunu\nTakkunu takkunu paakaatha\nBakkunu bakkunu\nBakkunu bakkunu\nBakkunu bakkunu aakkaatha\n\nKick onnu kick onnu\nKick onnu kick onnu\nKick onnu irukkuthu paarvaiyila\nLook onnu look onnu\nLook onnu look onnu\nVituttu ponaa thappae illa\n\nUn sirippu adhu thaaru maaru\nUnna azhagula minja yaaru\nNaduvula antha ego mattum\nNamakulla venaam di\n\nMusically-laam bore-u\nNaan compose panren paaru\nTeam oda tune pottu\nPaada poren di\n\nVaayen...\nOnna sernthu povom\nOru dating meeting\nVaaya.. konjam konaya vechi\nSelfie edukatta\nPaaren...en kannula kaadhala\nThaayen oru mutham onnu\nOk thaan neeyum sonna\nHusband aagatta\n\nTakkunu takkunu\nTakkunu takkunu\nTakkunu takkunu paakaatha\nBakkunu bakkunu\nBakkunu bakkunu\nBakkunu bakkunu aakkaatha\n\nKick onnu kick onnu\nKick onnu kick onnu\nKick onnu irukkuthu paarvaiyila\nLook onnu look onnu\nLook onnu look onnu\nVituttu ponaa thappae illa\n\nChorus : Ho ho ho ho ho ho ho ho........."
    },
    {
        id: 13,
        title: "Vizhi Moodi Yosithal",
        lyrics: "{Vizhi moodi yosithaal\nAngeyum vanthaai\nMunnae munnae\n\nVizhi moodi yosithaal\nAngeyum vanthaai\nMunnae munnae\n\nThaniyaaga pesidum\nSanthosam thanthaai\nPennae pennae\n\nAdi idhu pol\nMazhai kaalam\nEn vaazhvil varumaa\n\nMazhai kiliyae\nMazhai kiliyae\nUn kannai kandenae\n\nVizhi vazhiyae\nVizhi vazhiyae naan\nEnnai kandenae senthenae } x2\n\nKadalaai pesidum\nVaarthaigal yaavum\nThuliyaai thuliyaai kuraiyum\n\nMounam pesidum\nBaasaigal matum\nPurindhidumae\n\nThaanaai endhan\nKaalgal irandum undhan\nThisaiyil nadakum\n\nThooram neram\nKaalam ellam surungidumae\n\nIndha kaadhal\nVandhu vitaal nam\nThegam midhandhidumae\n\nVinnodum mugilodum\nVilaiyadi thirindhidumae\nOh oh oh .. \n\nVizhi moodi yosithaal\nAngeyum vanthaai\nMunnae munnae\n\nThaniyaaga pesidum\nSanthosam thanthaai\nPennae pennae\n\nAdi idhu pol\nMazhai kaalam\nEn vaazhvil varumaa\n\n{ Mazhai kiliyae\nMazhai kiliyae\nUn kannai kandenae\n\nVizhi vazhiyae\nVizhi vazhiyae naan\nEnnai kandenae } (2) senthenae ..."
    },
    {
        id: 14,
        title: "Sakkarakatti",
        lyrics: "Adiyae Sakkarakatti\nNenjukula Stickera Otti\nEnatha Enga Kooti Poriyo Nee\nAdiyae Aahaan\nAdiyae Venam\n\nAaan Adiyae Sakkarakatti\nNenjukula Stickera Otti\nEnatha Enga Kooti Poriyo Nee\n\nNeetha En Vellakatti\nVaadi En Chellakutti\nUnathan Unathan Theduren Naan\n\nNaanum Thedipaardhen\nUlagam Thandi Paardhen\nUnaai Pol Azhagiyathan Paarthadiladi..\n\nKavitha Paadi Paardhen\nKathakali Aadi Paardhen\nAdiyae Enna Konjam Paathu Selladi...\n\nVaa En Anjala\nNaa Unna Kenjuraen\nNee Ena Konjatha Vaadi Pulla\n\nVaa En Anjala\nNaa Unna Kenjuraen\nKadhal Konjama Thadi Pulla\n\nVaa En Anjala\nNaa Unna Kenjuraen\nNee Ena Konjatha Vaadi Pulla\n\nVaa En Anjala\nNaa Unna Kenjuraen\nKadhal Konjama Thadi Pulla\n\nNaa Sirika Nee Morachi Ena Paakum Pothu\nPennae En Manasukul Eppadi Irukum\nPuyalonju Mazha Penju Veyil Adikumpothu\nVeesidumae Kaathu Adi Athupol Irukum\n\nThonavilla Thonavilla\nEna Pathi Enakaethan Thonavilla\n\nKaanavilla Kaanavilla\nEn Manadu Enkita Ila Ila\n\nNaanum Thedipaardhen\nUlagam Thandi Paardhen\nUnaai Pol Azhagiyathan Paarthadiladi..\n\nKavitha Paadi Paardhen\nKathakali Aadi Paardhen\nAdiyae Enna Konjam Paathu Selladi..\n\nVaa En Anjala\nNaa Unna Kenjuraen\nNee Ena Konjatha Vaadi Pulla\n\nVaa En Anjala\nNaa Unna Kenjuraen\nKadhal Konjama Thadi Pulla\n\nVaa En Anjala\nNaa Unna Kenjuraen\nNee Ena Konjatha Vaadi Pulla\n\nVaa En Anjala\nNaa Unna Kenjuraen\nKadhal Konjama Thadi Pulla"
    },
    {
        id: 15,
        title: "Thendral Vanthu Theendumbothu",
        lyrics: "Thendral vanthu\nTheendum pothu\nEnna vannamo manasula\nThingal vanthu\nKaayum pothu\nEnna vannamo nenapula\n\nVanthu vanthu poguthamma\nEnnamellam vannam amma\nEnnagalukku yethapadi\nVannamellam maarumamma\nUnmaiyamma ullatha naanum sonnen\nPonnamma chinna kanne\n\nThendral vanthu\nTheendum pothu\nEnna vannamo manasula\nThingal vanthu\nKaayum pothu\nEnna vannamo nenapula\n\nEvarum sollaamalae\nPookkalum vaasam veesuthu\nUravum illaamalae\nIru manam yetho pesuthu\n\nEvarum sollaamalae\nKuyil ellaam thaena paaduthu\nEthuvum illaamalae\nManasellaam inippaa inikkuthu\n\nOda neeroda\nIntha ulagam athu pola\n\nOdam athu odum\nIntha kaalam athu pola\n\nNilaiyaa nillaathu\nNinaivil varum nirangalae\n\nThendral vanthu\nTheendum pothu\nEnna vannamo manasula\n\nThingal vanthu\nKaayum pothu\nEnna vannamo nenapula\n\nVanthu vanthu poguthamma\nEnnamellam vannam amma\n\nEnnagalukku yethapadi\nVannamellam maarumamma\n\nUnmaiyamma ullatha naanum sonnen\nPonnamma chinna kanne\nThendral vanthu\nTheendum pothu\nEnna vannamo manasula\nThingal vanthu\nKaayum pothu\nEnna vannamo nenapula"
    },
    {
        id: 16,
        title: "Orasaadha",
        lyrics: "Oru murai enna paathu\noraa kannil pesu\nOru murai enna paathu\noraa kannil pesu\n\nNee nerungi vandha\nkadhal vaasam\nen usuru moththam\nunna pesum\n\nOrasadha usurathan\nurukkaadha manasathan\nalasaatha, en satta kizhinji\nveliye parakkum idhayam\n\nVerukkaatha, kanavellaam\nsirikkaatha\nenavittu velagaatha\nthariketta manasu\nunna thaedi alaiyum\n\nadiye...\nadiye...\nadiye..\n\nOtti irundha nizhal\nottaama un pinna alaiyum\nun mutta muli moracha\nmunnooru oosi ulla irangum\n\nKattuveeriyanukku\nkadhal onnu vandha adangum.\nen kutti idhayathula\nnee thonda pakkura surangam\n\nNeeyum enna neengi pona\nneela vaanam kanneer sindhum\npesaama thaan pogaathadi nee\npaasaangu thaan pannaathadi\n\nSathiyama un nenappil\nmoochu mutti thikkurendi\nkovam yethi kollaathadi\nkoththi koththi thinnaathadi\n\nOrasadha usurathan\nurukkaadha manasathan\nalasaatha, en satta kizhinji\nveliye parakkum idhayam\n\nVerukkaatha, kanavellaam\nsirikkaatha\nenavittu velagaatha\nthariketta manasu\nunna thaedi alaiyum\n\nadiye...\nadiye...\n\nOrasadha usurathan\nurukkaadha manasathan\nalasaatha, en satta kizhinji\nveliye parakkum idhayam\n\nVerukkaatha, kanavellaam\nsirikkaatha\nenavittu velagaatha\nthariketta manasu\nunna thaedi alaiyum\n\nadiye.."
    },
    {
        id: 17,
        title: "Visiri",
        lyrics: "Rappap paa pare paparaa\nRappap paa pare paparaa\nRappap paa pare paparaa\nRappap paa pare paparaa\n\nEthuvarai pogalaam\nEndru nee sollavendum\nEndruthaan... vidamal ketkiren...\n\nThaen muthangal mattumae\nPothum yendru solvadhaal\nThodaamal pogiren...\n\nYaar yaaro kanaakkalil\nNaalum nee sendru ulaavukindraval\nNee kaanum kanaakkalil varum\nOr aanendraal naandhaan ennaalilum\n\nPoongaatrae nee veesaathae\nOooooo..\nPoongaatrae nee veesaathae\nNaan dhaan ingae visiri\n\nEn veetlil nee nirkindraai\nAthai nambaamal ennai killikonden\nThottathil nee nirkindraai\nUnnai poovendru enni koiyyachendren..\n\nPugazh poomaalaigal\nThaen solaigal\n\nNaan kanden yen un pin vandhen\nPerum kasolaigal ponmaalaigal\nVendaamae nee vendumendren\nUyirae...\n\nNetrodu en vegangal\nSirutheeyaga maari thoonga kanden\nKatrodu en kobangal\nOru thoosaaga maari pogakanden\n\nUnai paarkatha naan\nPesatha naan\nEn vazhvil nee naanendru naan\nDhinam nee vandhathaal\nThol thanthathaal\nAanen naan aannadha pen dhaan\nUyirae...\n\nHo ho hooh..\nEthuvarai pogalaam\nEndru nee sollavendum\nEndruthaan.. vidamal ketkiren\n\nThaen muthangal Mattumae\nPothum endru solvadhaal\nThodaamal pogiren\n\nUn pondra ilainganai\nManam erkamal marupadhae pizhai\nKanden un alaadhi thooimaiyai\nEn kanpaarthu pesum peraanmaiyai\n\nPoongaatrae nee veesaathae\nOoooooo..\nPoongaatrae nee veesaathae\nNaan dhaan ingae visiri\n\nRuth thu thu ruth thu ru ruuuu\nRuth thu thu ruth thu ru ruuuu\nRuth thu thu ruth thu ru ruuuu\nRuth thu thu ruth thu ru ruuuu"
    },
    {
        id: 18,
        title: "Adada Mazhaida",
        lyrics: "Thantha nae thantha nanae\nThantha naanae thana nae\nThantha nae thantha nanae\nThantha nanae naaaaaa......\n\nAdadaa mazhaidaa adai mazhaidaa\nAzhagaa sirichaa puyal mazhaidaa\nAdadaa mazhaidaa adai mazhaidaa\nAzhagaa sirichaa puyal mazhaidaa\n\nMaari maari mazhaiyadikka\nManasukkulla kodaipidikka\nKaalgal naalaachu kaigal ettaachu\nEnna aachu edhaachu edhedho aayaachu\n\nMayil thogai pola\nIva mazhaiyil aadumbodhu\nRayil paalam pola\nEn manasum aadum paaru\nEnna aachu edhaachu edhedho aayaachu\n\nAdadaa mazhaidaa adai mazhaidaa\nAzhagaa sirichaa puyal mazhaidaa\n\n\nPaattu paattu paadaadha paattu\nMazhaithaan paadudhu ketkaadhappaattu\nUnnai ennai serthu vacha\nMazhaikkoru salaam podu\nEnnai konjam kaanalayae\nUnakkulla thedippaaru\n\nMandhiram pola irukku\nPudhu thandhiram pola irukku\nBambaram pola enakku\nThalaimathiyil suthudhu kirukku\nDhevadhai engae en dhevadhai engae\nAdhu santhoshamaai aadudhu ingae\n\n\nAdadaa mazhaidaa adai mazhaidaa\nAzhagaa sirichaa anal mazhaidaa\nAdadaa mazhaidaa adai mazhaidaa\nAzhagaa sirichaa anal mazhaidaa\n\nMaari maari mazhaiyadikka\nManasukkulla kodaipidikka\nKaalgal naalaachu kaigal ettaachu\nEnna aachu edhaachu edhedho aayaachu\n\nMayil thogai pola\nIva mazhaiyil aadumbodhu\nRayil paalam pola\nEn manasum aadum paaru\nEnna aachu edhaachu edhedho aayaachu\n"
    },
    {
        id: 19,
        title: "Pogathe Pogathe",
        lyrics: "Pogaadhae pogaadhae nee irunthaal naan iruppen\nPogaadhae pogaadhae nee pirinthaal naan irappen\n\nUnnodu vaalntha kaalangal yaavum\nKanavaai ennai mooduthadi...\nYaar endru neeyum ennai paarkkum pothu\nUyirae uyir poguthadi\n\nKallaraiyil kooda jannal ondru vaithu\nUndhan mugam paarpenadi..\n\nPogaadhae pogaadhae nee irunthaal naan iruppen\nPogaadhae pogaadhae..hey nee pirinthaal naan irappen\n\nAlagaana neram adhai neethaan koduthaai\nAliyaatha sogam athaiyum nee thaan koduthaai\nKan thoongum neram paarthu kadavul vanthu ponathu pol\nYen vaalvil vanthae aanai yemaattram thaangalaiyae\nPennae nee illaamalllll....\nBooloagam iruttiduthae...ae..\n\nPogaadhae pogaadhae nee irunthaal naan iruppen\nPogaadhae pogaadhae.. nee pirinthaal naan irappen..."
    },
    {
        id: 20,
        title: "Vaadi Pulla Vaadi",
        lyrics: "Karisal Kaatu Kaathal Kaatchi\nEthuku Nenje Ithana Pechi\nOoru Oram Aalanthoppu\nAthile Vaazhum Kiligalin Kathaithaane\nUn Kaathal Endraachu\nUn Pechu En Moochu\nAdi Unnai Pathi Nitham Ninaithidum\nPadi Aachu\nUn Kovam Athil Veppam\nUn Ullam Pari Sutham\nAdi Nee Pirintha Nodiyile Enthan Uyir Paspam\nOru Vaarthau Sollava\nUn Idathil Naan Endrendrum\nThurathi Varuven Penne Unnaithaan\nAdi Ennai Vittu Engae Pogindraai Penne\nIpa Ennai Thedi Neeyum Odi\nVaadi Vaadi Vaadi Vaadi\nVaadi Pulla Vaadi\nVaadi Pulla Vaadi\nOnna Mattum Nenachiruken En Nenjukulla\nVaadi Pulla Vaadi\nVaadi Pulla Vaadi\nOnna Mattum Nenachiruken En Nenjukulla\nVaadi Pulla Vaadi\nVaadi Pulla Vaadi\nOnna Mattum Nenachiruken En Nenjukulla\nVaa Nila Nila Neethaane Enthan Vennila\nVaa Nila Nila Neethaane Enthan Vennila\nVaa Nila Nila Neethaane Enthan Vennila\nVaa Nila Nila Neethaane Enthan Vennila\nKaathirintha Kaathulukku Solladi Nal Vazhi\nUn Kaathal Enthan Vaazhvai Sethikkidum Oor Uli\nNee Indri Enthan Vaazhkai Thanil Illai Adi Oli\nPorikka Mudiyavillai Ithu Kaathal Thantha Vali\nVaa Penne Ennai Paar\nOru Mutham Ondru Thaa\nUnnai Mattum Ninaithathu Intha\nIthayam Allavaa Allavaa\nSiru Kaneer Thuli Enthan Kannin Oram\nKaathalithu Tholviyutrathaal Nenjukkum Baaram\nKanneril Vaazhvathaal Naamum\nInge Meengal Thaan\nMithitha Kaathal Endru Kadalil Poi Seralaam\nSerum Munn Matham Endra Valai Yil Naam Vizhunthaal\nUyir Pirinthaal Kaathal Murinthaal\nOndre Ondrai Mattum Ninaivil Nee Vaithu Kol\nIngillai Endraal Enna Sorgathil Naam Seralaam\nSorgathilum Saathi Matham Endru Pirithaal\nSorgame Thevai Illai Naragathil Vaazhalaam\nVaadi Pulla Vaadi\nVaadi Pulla Vaadi\nOnna Mattum Nenachiruken En Nenjukulla\nVaadi Pulla Vaadi\nVaadi Pulla Vaadi\nOnna Mattum Nenachiruken En Nenjukulla\nVaadi Pulla Vaadi\nVaadi Pulla Vaadi\nOnna Mattum Nenachiruken En Nenjukulla\nVaa Nila Nila Neethaane Enthan Vennila\nVaa Nila Nila Neethaane Enthan Vennila\nVaa Nila Nila Neethaane Enthan Vennila\nVaa Nila Nila Neethaane Enthan Vennila"
    },
    {
        id: 21,
        title: "What a Karuvaad",
        lyrics: "{What a karvaad..what a karvaad\nWhat a karvaadu.. what a karvaad} (2)\n\nSutta vada pochu da.. what a karvaad\nPattam kilinji pochu da.. what a karvaad\nEn kattam alinji pochu da.. what a karvaad\nRomba mattam thattiyaachu da.. what a karvaad\n\nNaan karuthu solla poren da\nWhat a, what a, what a kar ..\nWhat a, what a, what a kar ..\nWhat a, what a, what a kar ..\nWhat a, what a, what a kar ..\n\n{What a karvaad..what a karvaad\nWhat a karvaadu.. what a karvaad} (2)\n\nPodhum pa off pannikalaama\nKaakka karuppu... batta seruppu\nSharppa iru da.. puriyadhu\nMaangaaai pulikkum.. maambalam inikum\nIdhu thaan vazhka maaraadhu\n\nLove kidachaa vachika vachika vachika vachika\nLove pochaa vittududaa\n\nLucku adichaa allikka allikka allikka\nLucku pochaa thallika da\n\nPerumaalaeeeeehhhhhh.. oh perumaalae\nUnna nambi thaanae kalangaama irukken pa\nVazhi thaedi suthurenae naanu\nUn paarva en mela ada thirumbavae thirumbala\n\n{What a karvaad..what a karvaad\nWhat a karvaadu.. what a karvaad} (2)\n\nSutta vada vada vada vada..\nSutta vada vada vada vada..sutta vada pochu da..what a karvaad\nEn pattam kilinji pochu da.. what a karvaad\nEn kattam alinji pochu da.. what a karvaad\nRomba mattam thattiyaachu da.. what a karvaad\n\nNaan karuthu solla poren da\nAaniyae pudunga vendaam"
    },
    {
        id: 22,
        title: "Venam Machan Venam",
        lyrics: "{Vanjaram meenu vavaalu\nKidacha keluthi viraalu\nIruku meesai yeraalu\nIrangi kalaku gopaalu } (2)\n\n{ Venam machan venam\nIndha ponnunga kaadhalu\nAdhu moodi thorakum podhae\nUnna kavukum quaterru } (2)\n\nKadala polae kaadhal\nOru saltu wateru\nAdhu konjam karikum podhae\nNee thooki potudu\n\n{ Mummy sonna ponna\nKatina torcher illada\nNeeyum davadikum ponna\nKatina trouser avurunda } (2)\n\nKanna kalanga vaikum\nFigureu venanda\nNamaku kanneer anjali poster\nOttum nanban pothunda\n\n{ Vanjaram meenu vavaalu\nKidacha keluthi viraalu\nIruku meesai yeraalu\nIrangi kalaku gopaalu } (2)\n\n{ Bikela thinamum onnaa ponom\nBackla ippo avala kaanom\nBeachla sugama kadala potom\nKadalukum ippo kanneer mutum } (2)\n\nKaadhalikum bodhu\nAda kannu theriyadhu\nUn kanna muzhichikita\nAnga kaadhal kidaiyathu\n\nAva ponaalae pona\nThanneera vitu meena\nNaan kaayam patta maina\nIppo paaduren gaana\n\nFigureu sugaru maathiri\nJanaku janaku vavaalu\nNatpu thadupu ooseeda\nJanaku jaanu gopalu\n\nFigureu sugaru maathari\nPasanga odamba urukidum\nNatpu thadupu ooseeda\nOdancha manasa thethidum\n\nVenam machan venam\nIndha ponnunga kaadhalu\nAdhu moodi thorakum podhae\nUnna kavukum quaterru\n\nKadala polae kaadhal\nOru saltu wateru\nAdhu konjam karikum podhae\nNee thooki potudu\n\nPaadhiyil vandha ponna nambi\nAadhiyil valarntha natpa viten\nThethiya polae kizhichi putta\nDevathai avala nambi ketten\n\nTholu matum vella\nUnna kavuthuputa mella\nYenna panni yenna ada\nAppavae naan sonnen\n\nAva potaalae potaa\nNalla dhindukallu poota\nOru chaavi kondu vaada\nEnna thorandhu vedenda\n\nKannula maiya veipaada\nAdhula poiya veipaada\nUdhatil saayam veipaada\nUnaku kaayam veipaada\n\nKannula maiya veipaada\nAdhula poiyo poiyaiyo\nUdhatil saayam veipaada\nUnaku kaiyo kaiyaiyo\n\nVenam machan venam\nIndha ponnunga kaadhalu\nAdhu moodi thorakum podhae\nUnna kavukum quaterru\n\nKadala polae kaadhal\nOru saltu wateru\nAdhu konjam karikum podhae\nNee thooki potudu\n\n{ Mummy sonna ponna\nKatina torcher illada\nNeeyum davadikum ponna\nKatina trouser avurunda } (2)\n\nKanna kalanga vaikum\nFigureu venanda\nEnaku kanneer anjali poster\nOttum nanban pothunda"
    },
    {
        id: 23,
        title: "Jalsa",
        lyrics: "\nVaazhkaiya yosingada....\nThala ezhutha nalla vaasingada\nYosichu paarungada\nEllorum onna serungada\nIrukkura varaikkum anubhavikka\nIlamai yeththukkada\nVarugira varaikkum laabamada\nVasathiya thedungada... go....\n\nIni jalsa pannungada....\nGujaala jilpa kaattungada\nIni jalsa pannungada...\nGujaala jilpa kaatungada\n\n\nGnyaabagam vanthathada....\nAndha naal gnayaabagam vanthathada\nNanbanai vida oruthan\nLifekku thevai illaiyada\nNatpukku kooda karpugal undu\nNalla therinjukkada\nArputhamaana nanbargal serntha\nVettrigal kumiyumada\nNam vettrigal kumiyumada\n\nIni jalsa pannungada....\nGujaala jilpa kaattungada\nIni jalsa pannungada...\nGujaala jilpa kaatungada\n\nUzhaikkum kaiya nambi\nNaalaikku ulagamae irukkuthada\nUnmaikku poraadi kural kodutha\nOorae vanangumada\nNaan ungal thozhan nee enthan nanban\nPirivae illaiyada\nNaalaiya ulagam ilaignyargal kaiyil\nNambikkai vaiyingada\nEn mela nambikkai vaiyingada\nVaa....\n\nIni jalsa pannungada....\nGujaala jilpa kaattungada\nIni jalsa pannungada...\nGujaala jilpa kaatungada\n\n\nKaadhal vanthichuna\nMugathila color pala theriyumada\nKannaadi munnaadi nee ninna\nKavarchiyum thonumada\nKaadhali idam than kavalaigal theerum\nKaadhal pannungada\nAndha kalyaanam mattum late a yosi\nNalla irukkumada\nUn vaazhkai nalla irukkumada\n\nIni jalsa pannungada....\nGujaala jilpa kaattungada\n\nIni jalsa pannungada...\nGujaala jilpa kaatungada\n\nDaavula vizhunthaakka\nManasu novula azhugumada\nTheevula iruppathupol\nDhisaiyae theriyaama pogumada\nInnaikki sirippa naalaikku moraippa\nInnamum irukkuthada\nAndha rodhana namakku ippo ethukku\nUshaara irunthukkada\nFigure a nambaama pozhachukkada\n\nIni jalsa pannungada....\nGujaala jilpa kaattungada\nIni jalsa pannungada...\nGujaala jilpa kaatungada\n\nVaazhkiaya yosingada\nThala ezhutha nalla vaasingada\n"
    }
];

// Helper to find song by ID
function getSongById(id) {
    return songs.find(s => s.id === id);
}